# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-20 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20161120_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpreference',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
